KTGK/KTGK/Models/Product.cs
namespace KTGK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Product")]
    public partial class Product
    {
        public int id { get; set; }

        [StringLength(100)]
        public string code { get; set; }

        [StringLength(100)]
        public string name { get; set; }

        [StringLength(100)]
        public string sort_name { get; set; }

        [StringLength(100)]
        public string note { get; set; }

        public int? category_id { get; set; }

        public virtual Category Category { get; set; }
    }

    public class viewProduct
    {
        public Product products { get; set; }
        public List<Category> categories { get; set; }
    }
}

KTGK/KTGK/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KTGK.Models;
using PagedList;

namespace KTGK.Controllers
{
    public class ProductsController : Controller
    {
        private ManageProduct db = new ManageProduct();

        // GET: Products
        public ActionResult Index(int page = 1 , int pageSize = 7 , int category_id = 0, string search="")
        {
            List<Category> categories = db.Categories.ToList();
            
            var products = db.Products.Include(p => p.Category).Where(e => e.name.Contains(search)).ToList();
            if (category_id != 0)
            {
                products = products.Where(e => e.category_id == category_id).ToList();
            }
            var productIncategory = from e in products
                                    join d in categories on e.category_id equals d.id

                                    select new viewProduct
                                    {
                                        products = e,
                                        categories = categories,
                                    };
           
            PagedList<viewProduct> result = new PagedList<viewProduct>(productIncategory, page, pageSize);
            return View(result);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.Categories, "id", "name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,code,name,sort_name,note,category_id")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.category_id = new SelectList(db.Categories, "id", "name", product.category_id);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.Categories, "id", "name", product.category_id);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,code,name,sort_name,note,category_id")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.Categories, "id", "name", product.category_id);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KTGK/KTGK/Views/Products/Create.cshtml
@model KTGK.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sort_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sort_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sort_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KTGK/KTGK/Views/Products/Delete.cshtml
@model KTGK.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sort_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sort_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KTGK/KTGK/Views/Products/Details.cshtml
@model KTGK.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sort_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sort_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.note)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KTGK/KTGK/Views/Products/Edit.cshtml
@model KTGK.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sort_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sort_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sort_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KTGK/KTGK/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model PagedList.IPagedList<KTGK.Models.viewProduct>
@using PagedList.Mvc;

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @using (Html.BeginForm("Index","Products",FormMethod.Get, new { id = "submitForm", name = "submitForm" }))
    {
        <input class="form-control" placeholder="search..." name="search" /> <hr />
        <button class="btn btn-danger" type="submit">Search</button><hr />
        <select class="form-control" name="category_id" onchange="SelectedIndexChanged()">
            <option value="0" selected>Tất cả</option>
            @foreach (var item in Model[0].categories)
                {
                    string check = Request.QueryString["category_id"] == item.id.ToString() ? "selected" : "";
                    <option value="@item.id" @check>@item.name</option>
                }
            
           
        </select>
    }
   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Name Category")
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].products.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].products.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].products.sort_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].products.note)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.products.Category.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.products.code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.products.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.products.sort_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.products.note)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.products.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.products.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.products.id })
        </td>
    </tr>
}

</table>

@Html.PagedListPager(Model, page => Url.Action("", new { page, pageSize = Model.PageSize }))

<script type="text/javascript">

    function SelectedIndexChanged() {
        //Form post
        document.submitForm.submit();
    }
</script> 